# Default Profile
[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_706_185_600  # Feb 1, 2025, 00:00 GMT
  bytecode_hash = "none"
  evm_version = "paris"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.25"
  src = "src"
  test = "test"
  fs_permissions = [
    { access = "read-write", path = "./broadcast/Deploy.s.sol/"}
  ]

# CI Profile (for GitHub Actions, pipelines, etc.)
[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

# Formatting Settings
[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

# Libraries & Remappings
remappings = [
  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
  "@warden/=lib/warden-agent-kit/"
]

# Fuzz Testing & Invariant Testing
[fuzz]
runs = 1_000

[invariant]
runs = 1_000
depth = 10

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
